# Wraps shaders/hlsl/*.hlsl into a header of raw string literals.
#
# The D3D11 backend compiles HLSL to DXBC at startup, so it needs the shader
# text rather than the .cso files D3D12 builds. Embedding it keeps that backend
# free of runtime shader assets while leaving shaders/hlsl as the one place the
# shaders are written.
#
# Run with: cmake -DHLSL_DIR=<dir> -DOUT=<header> -P EmbedHlsl.cmake

set(_out "// Generated by cmake/EmbedHlsl.cmake -- do not edit.\n")
string(APPEND _out "// Source: shaders/hlsl/*.hlsl\n\n")
string(APPEND _out "#ifndef ULTRAGUI_GENERATED_HLSL_EMBEDDED_H_\n")
string(APPEND _out "#define ULTRAGUI_GENERATED_HLSL_EMBEDDED_H_\n\n")
string(APPEND _out "namespace ugui {\n\n")

foreach(_name quad text video)
    file(READ "${HLSL_DIR}/${_name}.hlsl" _src)
    string(SUBSTRING "${_name}" 0 1 _head)
    string(TOUPPER "${_head}" _head)
    string(SUBSTRING "${_name}" 1 -1 _tail)
    # The delimiter must not appear in the shader text; ")ugui_hlsl\"" cannot,
    # since HLSL has no raw string literals.
    string(APPEND _out
        "static const char* k${_head}${_tail}Hlsl = R\"ugui_hlsl(\n${_src})ugui_hlsl\";\n\n")
endforeach()

string(APPEND _out "}  // namespace ugui\n\n")
string(APPEND _out "#endif  // ULTRAGUI_GENERATED_HLSL_EMBEDDED_H_\n")

file(WRITE "${OUT}" "${_out}")
